CAMERA_DEVICE_NUM = 0
CAMERA_COOLDOWN_TIMEOUT_SEC = 1

CAMERA_FOCUS_VALUE = 680 # From 0 to 800
CAMERA_ZOOM_VALUE = 100

CAMERA_CONTRAST_VALUE = 140
CAMERA_BRIGHTNESS_VALUE = 128
CAMERA_SHARPNESS_VALUE = 140

CAMERA_RESOLUTION_WIDTH = 640
CAMERA_RESOLUTION_HEIGHT = 480


CAPTURE_PAUSE_SEC = 300

SAVE_RAW_CAPTURES = False
RAW_CAPTURES_DIR = "captures"

YOLO_MODEL_FILE = "ant_best_yolov8.pt"
YOLO_CONFIDENCE_VALUE = 0.20
YOLO_IOU_VALUE = 0.40
YOLO_SAVE_IMG = False


RESULT_DIR = "static/result"
RESULT_IMG_NAME = "result.png"
RESULT_JSON_NAME = "result.json"
